# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class Person(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, first_name: str=None, last_name: str=None, username: str=None, date_of_birth: date=None, last_time_online: datetime=None):  # noqa: E501
        """Person - a model defined in Swagger

        :param first_name: The first_name of this Person.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this Person.  # noqa: E501
        :type last_name: str
        :param username: The username of this Person.  # noqa: E501
        :type username: str
        :param date_of_birth: The date_of_birth of this Person.  # noqa: E501
        :type date_of_birth: date
        :param last_time_online: The last_time_online of this Person.  # noqa: E501
        :type last_time_online: datetime
        """
        self.swagger_types = {
            'first_name': str,
            'last_name': str,
            'username': str,
            'date_of_birth': date,
            'last_time_online': datetime
        }

        self.attribute_map = {
            'first_name': 'firstName',
            'last_name': 'lastName',
            'username': 'username',
            'date_of_birth': 'dateOfBirth',
            'last_time_online': 'lastTimeOnline'
        }

        self._first_name = first_name
        self._last_name = last_name
        self._username = username
        self._date_of_birth = date_of_birth
        self._last_time_online = last_time_online

    @classmethod
    def from_dict(cls, dikt) -> 'Person':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Person of this Person.  # noqa: E501
        :rtype: Person
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self) -> str:
        """Gets the first_name of this Person.


        :return: The first_name of this Person.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this Person.


        :param first_name: The first_name of this Person.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this Person.


        :return: The last_name of this Person.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this Person.


        :param last_name: The last_name of this Person.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def username(self) -> str:
        """Gets the username of this Person.


        :return: The username of this Person.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Person.


        :param username: The username of this Person.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501
        if username is not None and len(username) > 64:
            raise ValueError("Invalid value for `username`, length must be less than or equal to `64`")  # noqa: E501
        if username is not None and len(username) < 8:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `8`")  # noqa: E501
        if username is not None and not re.search(r'[a-z0-9]{8,64}', username):  # noqa: E501
            raise ValueError("Invalid value for `username`, must be a follow pattern or equal to `/[a-z0-9]{8,64}/`")  # noqa: E501

        self._username = username

    @property
    def date_of_birth(self) -> date:
        """Gets the date_of_birth of this Person.


        :return: The date_of_birth of this Person.
        :rtype: date
        """
        return self._date_of_birth

    @date_of_birth.setter
    def date_of_birth(self, date_of_birth: date):
        """Sets the date_of_birth of this Person.


        :param date_of_birth: The date_of_birth of this Person.
        :type date_of_birth: date
        """

        self._date_of_birth = date_of_birth

    @property
    def last_time_online(self) -> datetime:
        """Gets the last_time_online of this Person.


        :return: The last_time_online of this Person.
        :rtype: datetime
        """
        return self._last_time_online

    @last_time_online.setter
    def last_time_online(self, last_time_online: datetime):
        """Sets the last_time_online of this Person.


        :param last_time_online: The last_time_online of this Person.
        :type last_time_online: datetime
        """

        self._last_time_online = last_time_online
